stages:
  - build
  - test
  - deploy

maven-build:
  stage: build
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn clean compile

# Test delle classi base (Player e Bank)
test-core:
  stage: test
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn test -Dtest=PlayerTest,BankTest
  artifacts:
    when: always
    reports:
      junit: "target/surefire-reports/TEST-ch.supsi.monopoly.*.xml"
    paths:
      - target/surefire-reports/

# Test di tutte le tipologie di Caselle (Package board)
test-board-logic:
  stage: test
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn test -Dtest=BoxAssetsTest,BoxLuxuryTest,BoxParkingTest,BoxPropertyTest,BoxStartTest,BoxStationTest
  artifacts:
    when: always
    reports:
      junit: "target/surefire-reports/TEST-ch.supsi.monopoly.board.*.xml"
    paths:
      - target/surefire-reports/

# Test delle utility e del formatter (Package cli e utilities)
test-utilities:
  stage: test
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn test -Dtest=TextFormatterTest,PlayerFactoryTest,ScannerUtilitiesTest
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-ch.supsi.monopoly.cli.*.xml
        - target/surefire-reports/TEST-ch.supsi.monopoly.utilities.*.xml
    paths:
      - target/surefire-reports/

generate-docs:
  stage: deploy
  image: maven:3.9.3-eclipse-temurin-17
  script:
    - mvn javadoc:javadoc
  artifacts:
    name: "javadoc-monopoly"
    paths:
      - doc/  # Esporta la cartella doc come artefatto scaricabile da GitLab
    expire_in: 1 week