# Board
board.columns=11
board.rows=11

#
box.jail.time=3
box.luxury.tax=200
box.start.bonus=100

box.toll.min=50
box.toll.max=150
box.height.player.row=5
box.height.total=7



# Bank
bank.balance=1000000
bank.contribution=2000

# Game
game.players.number=4


