@startuml

class Player {
  - name: String
  - sign: char
  - balance: int
  - coordinate: int
  + Player(name: String, sign: char): constructor
  + move(): void
  + toString(): String
  + getName(): String
  + getSymbol(): char
  + getBalance(): int
  + isBroke(): boolean
}

package cli {
    enum Color {
        RESET
        BLACK
        RED
        GREEN
        YELLOW
        BLUE
        PURPLE
        CYAN
        WHITE
    }

    abstract class TextColorizer {
        + color(text: String, color: Color): String
    }
}

abstract class Bank {
  - {static} balance: int
  + {static} distribute(player: Player): void
  + {static} debit(player: Player, box: Box): void
}

abstract class Dice {
  - {static} faces: int[]
  + {static} launch(): int
}

class Game {
  - isPlaying: boolean
  - PLAYERS_NUMBER: int
  - players: Player[]
  - board: Board
  - gameLoop(): void
  + Game(scanner: Scanner): constructor
  + start(scanner: Scanner): void
  + gameItself(scanner: Scanner): void
  + getSignsAtIndex(index: int): char[]
  + menu(): void
  + rollDice(): int
  + getIsPlaying(): boolean
}

package board{
    package interfaces {
        interface Taxable {
          + tax(player: Player): void
        }

        interface Refundable {
          + refund(player: Player): void
        }
    }

    class Board {
      - boxes: Box[]
      + Board(): constructor
    }

    class Box {
      # {static} MIN_TOLL: int
      # {static} MAX_TOLL: int
      # value: int
      # name: String
      # description: String
      - representation: String[]
      + Box(value: int, name String): constructor
      + Box(name: String): constructor
      - {static} generateRandomNum(): int
      - updateRepresentation(): void
      + draw(index: int): String
      + toString(): String
      + setDescription(): void
      + getValue(): int
      + getName(): String
      + getDescription(): String
    }

    class BoxProperty {
      + BoxEstate(name: String): constructor
      + tax(player: Player): void
      + applyEffect(player: Player): void
      + toString(): String
    }

    class BoxAssets {
      + BoxHeritage(name: String): constructor
      + tax(player: Player): void
      + applyEffect(player: Player): void
      + toString(): String
    }

    class BoxLuxury {
      - LUXURY_TAX_AMOUNT: int
      + BoxLuxury(name: String): constructor
      + tax(player: Player): void
      + applyEffect(player: Player): void
      + toString(): String
    }

    class BoxParking {
      + BoxParking(name: String): constructor
      + applyEffect(player: Player): void
    }

    class BoxStart {
      + BoxStart(name: String): constructor
      + refund(): void
      + applyEffect(player: Player): void
      + {static} getBonus(): int
    }

    class BoxStation {
      + BoxStation(str: String): constructor
      + applyEffect(player: Player): void
    }
}

Box <|-- BoxProperty
Box <|-- BoxAssets
Box <|-- BoxLuxury
Box <|-- BoxParking
Box <|-- BoxStart
Box <|-- BoxStation

Taxable <|.. BoxLuxury
Taxable <|.. BoxAssets
Taxable <|.. BoxStation
Taxable <|.. BoxProperty

Refundable <|.. BoxStart

abstract class ScannerUtilities {
  + {static} getInputString(scanner: Scanner, message: String): String
}

@enduml