@startuml

class Player {
  - name: String
  - sign: char
  - balance: int
  - position: int
  + Player(name: String, sign: char): constructor
  + move(): void
  + print(): void
  + isBroke(): boolean
  + getSymbol(): char
}

package cli {
    enum Color {
        RESET
        BLACK
        RED
        GREEN
        YELLOW
        BLUE
        PURPLE
        CYAN
        WHITE
    }

    abstract class TextColorizer {
        + color(text: String, color: Color): String
    }
}

abstract class Bank {
  - {static} balance: int
  + {static} distribute(player: Player): void
  + {static} debit(player: Player, box: Box): void
}

abstract class Dice {
  - {static} faces: int[]
  + {static} launch(): int
}

class Game {
  - PLAYER_NUMBER: int
  - players: Player[]
  - gameboard: GameBaord
  - gameLoop(): void
  + Game(): constructor
}

class Baord {
  - boxes: Box[]
  + Board(): constructor
}

interface Taxable {
  + tax(player: Player): void
}

class Box {
  - {static} MIN_TOLL: int
  - {static} MAX_TOLL: int
  - value: int
  + name: String
  - rappresentation: String[]
  + Box(name: String): constructor
  - generate(): void
  + getToll(): int
  + getName(): String
}

class BoxEstate {
  - {static} MIN_TOLL: int
  - {static} MAX_TOLL: int
  + BoxEstate(str: String): constructor
  + applyEffect(player: Player): void
  + {static} generateRandomNum(): int
}

class BoxHeritage {
  - {static} TAX: int
  + BoxHeritage(): constructor
  + applyEffect(player: Player): void
}

class BoxLuxury {
  + BoxLuxury(): constructor
  + tax(player: Player): void
}

class BoxParking {
  - {static} MONEY: int
  + BoxParking(): constructor
  + applyEffect(player: Player): void
}

class BoxStart {
  - {static} BONUS: int
  + BoxStart(): constructor
  + applyEffect(player: Player): void
  + {static} getBonus(): int
}

class BoxStation {
  - {static} MIN_TOLL: int
  - {static} MAX_TOLL: int
  + BoxStation(str: String): constructor
  + applyEffect(player: Player): void
  + {static} generateRandomNum(): int
}

Box <|-- BoxEstate
Box <|-- BoxHeritage
Box <|-- BoxLuxury
Box <|-- BoxParking
Box <|-- BoxStart
Box <|-- BoxStation

Taxable <|.. BoxLuxury

abstract class ScannerUtilities {
  + {static} getInputString(scanner: Scanner, message: String): String
}

@enduml